# basic settings

DRAFT_OPEN = True
TOURNAMENT_NAME = "2026 Fantasy Regionals"
# RANKING_DATA = "data/test.csv"
RESULTS_TEAMS_TAB = "Sheet1"
RESULTS_SCORES_TAB = "Scores v2"
ROSTER_SIZE = 9
BUDGET_LIMIT = 100
MAX_GENDER_SIZE = 5
MIN_GENDER_SIZE = 4
MAX_TEAM_SIZE = 2
CAPTAIN_MULTIPLIER = 2
PIN_LENGTH = 4